### ISSUE TITLE
OilLibrary database generation failed

### ISSUE THREAD

**Issue by HanhHelen** [NOAA-ORR-ERD/OilLibrary#13]
Dear authors,
When I install Oil Library on Win 64, I have the problems like:

Installed c:\opendrift-master\oillibrary-master
Processing dependencies for oil-library==1.0.6
Finished processing dependencies for oil-library==1.0.6
OilLibrary database generation failed
Traceback (most recent call last):
  File "setup.py", line 170, in <module>
    init_db()
  File "setup.py", line 53, in init_db
    import oil_library.initializedb
  File "C:\opendrift-master\OilLibrary-master\oil_library\__init__.py", line 13,
 in <module>
    import sample_oils
  File "C:\opendrift-master\OilLibrary-master\oil_library\sample_oils\__init__.p
y", line 1, in <module>
    import oil_gas
  File "C:\opendrift-master\OilLibrary-master\oil_library\sample_oils\oil_gas.py
", line 9, in <module>
    'api': uc.convert('Density',
AttributeError: 'module' object has no attribute 'convert'

 I can’t manage. Can you help me?

**Comment by ChrisBarker-NOAA** [comment]
On a phone, do can’t look closely, but the “uc” module is the pynucos unit_converter package. Make sure you have the latest version:

https://github.com/NOAA-ORR-ERD/PyNUCOS

**Comment by HanhHelen** [comment]
I have this package.

**Comment by ChrisBarker-NOAA** [comment]
I can only imagine that something is wrong with the install of unit_conversion, as "convert" should be there.

Try (at a python or ipython prompt):

```
In [4]: import unit_conversion as uc

In [5]: uc.convert('Density',"API", "S", 11)
Out[5]: 0.9929824561403509
```
to make sure it's installed correctly.

and check the version:

```
In [6]: uc.__version__
Out[6]: '2.6.0'
```
Though "convert" has been there since the beginning, so older versions should work fine (at least in this context)

**Comment by HanhHelen** [comment]
After install PyNUCOS, I have the problem:
In [1]: import unit_conversion as uc

In [2]: uc.convert('Density',"API", "S", 11)
Traceback (most recent call last):

  File "<ipython-input-2-abec4bc8cb52>", line 1, in <module>
    uc.convert('Density',"API", "S", 11)

AttributeError: 'module' object has no attribute 'convert'

I am not sure where I have mistake.

**Comment by ChrisBarker-NOAA** [comment]
How did you install it? I just tried installing from source on a clean system here:

https://github.com/NOAA-ORR-ERD/PyNUCOS/releases

and it worked fine.

I used:

python2.7 setup.py install.

If you have more than one "python" installed on your system, make sure you are installing it into the correct one.

**Comment by HanhHelen** [comment]
I have only one Python 2.7 and install this package like your instruction, but it still has problem:
In [1]: import unit_conversion as uc

In [2]: uc.convert('Density',"API", "S", 11)
Traceback (most recent call last):

  File "<ipython-input-2-abec4bc8cb52>", line 1, in <module>
    uc.convert('Density',"API", "S", 11)

AttributeError: 'module' object has no attribute 'convert'
I don't know why. :((
